// ignore_for_file: avoid_web_libraries_in_flutter, deprecated_member_use

import 'dart:html' as html;
import 'dart:convert';

String _money(Map<String, dynamic>? value) =>
    value?['formatted'] as String? ?? 'RWF 0';

String _escapeHtml(String value) {
  return value
      .replaceAll('&', '&amp;')
      .replaceAll('<', '&lt;')
      .replaceAll('>', '&gt;')
      .replaceAll('"', '&quot;')
      .replaceAll("'", '&#39;');
}

String _buildRows(List<dynamic> items) {
  if (items.isEmpty) {
    return '<tr><td colspan="5">No entries</td></tr>';
  }

  return items.map((raw) {
    final item = raw as Map<String, dynamic>;
    return '''
      <tr>
        <td>${_escapeHtml(item['memberName'] as String? ?? 'Unknown')}</td>
        <td>${_escapeHtml(item['phone'] as String? ?? '-')}</td>
        <td>${_escapeHtml(item['email'] as String? ?? '-')}</td>
        <td>${_escapeHtml(_money(item['expectedAmount'] as Map<String, dynamic>?))}</td>
        <td>${_escapeHtml(_money(item['paidAmount'] as Map<String, dynamic>?))}</td>
      </tr>
    ''';
  }).join();
}

Future<void> printMonthlyReport(Map<String, dynamic> report) async {
  final period = report['period'] as String? ?? 'Monthly Report';
  final paidMembers = report['paidMembers'] as List<dynamic>? ?? const [];
  final peopleToPay = report['peopleToPay'] as List<dynamic>? ?? const [];
  final generatedAt = report['generatedAt'] as String? ?? '';

  final htmlContent =
      '''
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>MVCS Monthly Report</title>
    <style>
      body { font-family: Arial, sans-serif; padding: 32px; color: #111827; }
      h1, h2, h3 { margin: 0 0 12px 0; }
      .meta { margin-bottom: 24px; color: #4b5563; }
      .summary { display: flex; gap: 12px; margin-bottom: 24px; }
      .card { flex: 1; border: 1px solid #d1d5db; border-radius: 12px; padding: 16px; }
      .card h3 { font-size: 12px; color: #6b7280; letter-spacing: 0.08em; text-transform: uppercase; }
      .card .value { font-size: 24px; font-weight: 700; margin-top: 8px; }
      .green { color: #15803d; }
      .red { color: #dc2626; }
      .counts { display: flex; gap: 12px; margin-bottom: 24px; }
      table { width: 100%; border-collapse: collapse; margin-bottom: 24px; }
      th, td { border: 1px solid #e5e7eb; padding: 10px; text-align: left; font-size: 13px; }
      th { background: #f9fafb; }
      footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #e5e7eb; color: #6b7280; font-size: 12px; text-align: center; }
      @media print { button { display: none; } body { padding: 16px; } }
    </style>
  </head>
  <body>
    <h1>MVCS Monthly Contribution Report</h1>
    <div class="meta">
      <div><strong>Period:</strong> ${_escapeHtml(period)}</div>
      <div><strong>Generated At:</strong> ${_escapeHtml(generatedAt)}</div>
    </div>
    <div class="summary">
      <div class="card">
        <h3>Expected Amount</h3>
        <div class="value">${_escapeHtml(_money(report['expectedTotal'] as Map<String, dynamic>?))}</div>
      </div>
      <div class="card">
        <h3>Total Collected</h3>
        <div class="value green">${_escapeHtml(_money(report['collectedTotal'] as Map<String, dynamic>?))}</div>
      </div>
      <div class="card">
        <h3>Outstanding</h3>
        <div class="value red">${_escapeHtml(_money(report['outstandingTotal'] as Map<String, dynamic>?))}</div>
      </div>
    </div>
    <div class="counts">
      <div class="card">
        <h3>Paid People</h3>
        <div class="value green">${report['paidPeopleCount'] ?? 0}</div>
      </div>
      <div class="card">
        <h3>People To Pay</h3>
        <div class="value red">${report['peopleToPayCount'] ?? 0}</div>
      </div>
    </div>
    <h2>Paid Members</h2>
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Phone</th>
          <th>Email</th>
          <th>Expected</th>
          <th>Paid</th>
        </tr>
      </thead>
      <tbody>${_buildRows(paidMembers)}</tbody>
    </table>
    <h2>People To Pay</h2>
    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th>Phone</th>
          <th>Email</th>
          <th>Expected</th>
          <th>Paid</th>
        </tr>
      </thead>
      <tbody>${_buildRows(peopleToPay)}</tbody>
    </table>
    <footer>Generated by MVCS, a product of Higura Ventures</footer>
    <script>window.print();</script>
  </body>
</html>
''';

  final uri = Uri.dataFromString(
    htmlContent,
    mimeType: 'text/html',
    encoding: utf8,
  );
  html.window.open(uri.toString(), '_blank');
}
